# Generated by Django 5.2.13 on 2026-04-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id_bairro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_bairro', models.CharField(max_length=100, unique=True)),
                ('cep', models.CharField(max_length=8)),
                ('regiao', models.CharField(blank=True, max_length=200, null=True)),
                ('num_casa', models.CharField(blank=True, max_length=5, null=True)),
                ('ponto_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bairro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BannerPublicacao',
            fields=[
                ('id_banner', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('url_imagem', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banner_publicacao',
                'ordering': ['ordem', '-dt_criacao'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria_servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id_chamado', models.AutoField(primary_key=True, serialize=False)),
                ('num_protocolo', models.CharField(max_length=20, unique=True)),
                ('prioridade', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=500)),
                ('resolucao', models.CharField(blank=True, max_length=500, null=True)),
                ('nota_avaliacao', models.IntegerField(blank=True, null=True)),
                ('comentario_avaliacao', models.CharField(blank=True, max_length=500, null=True)),
                ('dt_abertura', models.DateTimeField()),
                ('dt_conclusao', models.DateTimeField(blank=True, null=True)),
                ('dt_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField()),
            ],
            options={
                'db_table': 'chamado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id_cidadao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('dt_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('senha_temporaria', models.CharField(blank=True, max_length=200, null=True)),
                ('perfil', models.CharField(default='CID', max_length=3)),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('num_endereco', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento_endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro_endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cep_endereco', models.CharField(blank=True, max_length=8, null=True)),
                ('dt_cadastro', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cidadao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotoChamado',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('url_foto', models.CharField(max_length=200)),
                ('dt_upload', models.DateTimeField()),
            ],
            options={
                'db_table': 'foto_chamado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoChamado',
            fields=[
                ('id_historico_chamado', models.AutoField(primary_key=True, serialize=False)),
                ('dt_alteracao', models.DateTimeField()),
                ('observacao', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'historico_chamado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.CharField(max_length=200)),
                ('lida', models.BooleanField(default=False)),
                ('arquivada', models.BooleanField(default=False)),
                ('dt_envio', models.DateTimeField()),
            ],
            options={
                'db_table': 'notificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id_secretaria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('gestor_responsavel', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'secretaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('prazo_amarelo_dias', models.IntegerField(default=15)),
                ('prazo_vermelho_dias', models.IntegerField(default=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id_servidor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('dt_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('senha_temporaria', models.CharField(blank=True, max_length=200, null=True)),
                ('perfil', models.CharField(max_length=3)),
                ('dt_cadastro', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'servidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusChamado',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'db_table': 'status_chamado',
                'managed': False,
            },
        ),
    ]
